### PR TITLE
fix: add missing `.argv`

### LINKED ISSUE #1: 🐛bug: `npx rashee gemini` is broken on node `v12.13.1`
## To reproduce

```
$ node --version
v12.13.1

$ npx rashee gemini
npx: installed 31 in 1.531s
require(...).command(...).argv.help is not a function
```

## Observed behavior

```
require(...).command(...).argv.help is not a function
```

## Expected behavior

Some horoscope info ^_^

### PR DESCRIPTION
**Pull request by bnb**
This is a slight adjustment to conform to the yargs API. Fixes #1.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -4,8 +4,8 @@ const https = require('https')
 const chalk = require('chalk')
 const argv = require('yargs')
   .command('sunsign', "sunsign to get today's horoscope for")
-  .argv.help('help')
   .help('help')
+  .argv
```
Comment (coilysiren) [inline index.js:8]: _(idle question, not a change request for this PR)_ If the code chained after `const argv = require('yargs')` can potentially cause user facing errors, then it seems like it would be worthwhile to put it inside of a function call? So you can do some error checking, if nothing else.

Comment (bnb) [reply index.js:8]: if you're talking about the chain itself, AFAIK there's no errors that _should_ potentially occur there - I may be misunderstanding, though. If you're talking about the code after the chaining, yes absolutely.
